apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ta-policy-request
  description: TA API
  tags:
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.1/webhook-example.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: guests
